#!/bin/ env bash
# Configure NGINX

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"

echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://youtube.com/ permanent;" /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server;/a error_page 404 /404.html;" /etc/nginx/sites-available/default
sudo sed -i "/location \/ {/a add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default

sudo service nginx restart
